################################
#      VelocityPteroPower      #
#         by TubYoub           #
################################

# Version of the configuration file
fileversion: 8

# Check for updates
# If true, the plugin will check for updates on startup.
# If a new version is available, a message will be sent to the console and to players with the permission "ptero.reload".
checkUpdate: true

# Choose which logging level should be used
# It depends on how much you want you're console to be filled with information from VPP
# For production you can safely set it to a higher level but for development/testing it is recommended to use a lower level
# 10 = Debug
# 20 = Info
# 30 = Warning
# 40 = Error
#default: 20
loggerLevel: 20

# How many Threads should be used to check the server status
# The more threads the more requests can be handled at the same time
# more threads = more resources used
# restart the server so changes take effect
# default: 10
apiThreads: 10

# print updated Rate Limit from the API response to console
# default: false
printRateLimit: false

# Choose the method to check if a managed server is online and ready.
# "VELOCITY_PING": Uses Velocity's built-in ping functionality. Requires the server
#                  to be registered in Velocity's config and accessible from the proxy.
#                  Less resource-intensive, doesn't use API rate limits. Might report
#                  online slightly before the server is fully joinable.
#                  Some simple Limbo servers might not report any Ping back suing this method.
# "PANEL_API": Uses the Pterodactyl/Pelican panel API to check the server's state.
#                    More accurate for actual server state ("running"), but uses API
#                    requests and counts towards rate limits.
# Default: "VELOCITY_PING"
serverStatusCheckMethod: "VELOCITY_PING"

# How long the ping to the server lasts, to check if its is online, until it times out (in milliseconds)
# default: 1000 (1 second)
pingTimeout: 1000

# How many retrys to shut down the server if the previous one failed
# default: 3
shutdownRetries: 3

# How long to wait before retrying to shut down the server (in seconds)
# default: 300
shutdownRetryDelay: 300

# How long to wait before shutting down the server if no player joined the server(in seconds)
# default: 300
# -1 = disabled
idleStartShutdownTime: 300

# How long to wait before allowing a player to start a server again (in seconds)
# default: 10
playerStartCooldown: 10

# Server Name from your limbo
# should be a configured server so it can be automatically started
# changeMe = not configured so limbo server won't be used
limboServer: changeMe

# How long (in seconds) the plugin should wait for the first check if the server is online
# The joinDelay (configured for each server) is still applied when the server is online before a
# player is automatically connected (so it doesn't affect this)
# Maybe consider changing this to a lower value if you have for example a
# limbo which is lightweight and starts fast
# default: 10
startupInitialCheckDelay: 10

# Servers to ignore when the stopIdle command is used
# THIS DOES NOT AFFECT forceStop
stopIdleIgnore:
  - hub
  - lobby
  - limbo

# If a player should receive a message when a server is not found in the config
# message will always be send to console
# default: false
serverNotFoundMessage: false

# Allow players with the permission "ptero.bypass" to bypass the whitelist when starting a server.
# This does not work to get around a whitelist because it is enforced by the backend server itself.
# default: true
whitelistAllowBypass: true

# How long (in minutes) VPP should wait in between checks for a new whitelist and enforce it (if enabled)
# default: 10
whitelistCheckInterval: 10

# Pterodactyl configuration
pterodactyl:
  # The URL of your pterodactyl panel
  # If you use Cloudflare Tunnel, you need to allow the ip in the bypass setting.
  url: "https://panel.example.com"
  # The client api key of your panel.
  # The Plugin supports the Pterodactyl & Pelican System.
  # Your API Key should either start with "ptlc_" or "peli_"
  # You can find the client api key in the "API Credentials" tab of the "Account" page.
  apiKey: "ptlc_000000000000000000000000000000000000000000"

# Per server configuration
# Make sure that the server names match the registered servers in the velocity.toml
servers:
  #server name
  example:

    # Panel server ID
    # You can find the Panel server ID in the URL of the server page.
    # For example, if the URL is https://panel.example.com/server/1234abcd, the server ID is 1234abcd.
    # For Pelican, you need the short UUID from Server Details.

    id: 1234abcd

    # The time in seconds to stop the server after the last player leaves.
    # If you don't want to stop the server automatically, set it to -1.
    # If you set it to 0, the server will be stopped immediately after the last player leaves.

    timeout: 30

    # The time (in seconds) VPP should wait before automatically connecting a player after a server successfully started.
    # For example when you have a plugin that needs a few seconds to fully load.... or smth else.
    startupJoinDelay: 10

    # If VPP should fetch the whitelist of the Server and enforce it when a player trys to start a server
    # default: false
    whitelist: false